# This file was generated by GoReleaser. DO NOT EDIT.
cask "nanoid" do
  desc "A simple, fast, and concurrent command-line tool for generating secure, URL-friendly unique string IDs using the NanoID Go implementation."
  homepage "https://github.com/sixafter/homebrew-nanoid-cli/"
  version "1.30.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nanoid"

  on_macos do
    on_intel do
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.30.0/nanoid_1.30.0_darwin_amd64.tar.gz",
        verified: "github.com/sixafter/nanoid-cli/",
        using: :homebrew_curl
      sha256 "f158af37d9ab671cef612a7640224fb432c4172041d89fcc76d9375d8d48c13f"
    end
    on_arm do
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.30.0/nanoid_1.30.0_darwin_arm64.tar.gz",
        verified: "github.com/sixafter/nanoid-cli/",
        using: :homebrew_curl
      sha256 "b003b1ca28fef4ffd89a21ef4330b574869a3f1261e97181225909f064580684"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.30.0/nanoid_1.30.0_linux_amd64.tar.gz",
        verified: "github.com/sixafter/nanoid-cli/",
        using: :homebrew_curl
      sha256 "c2e70ef32dbb0a7dfd03430d11ca9b9d0fd810f5bf8be02c876f91ba1171cf1e"
    end
    on_arm do
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.30.0/nanoid_1.30.0_linux_arm64.tar.gz",
        verified: "github.com/sixafter/nanoid-cli/",
        using: :homebrew_curl
      sha256 "b57d557f1410dd114c1881e03146f20cd3919d72e15e241bcc47ca276e6bb3e8"
    end
  end

  # No zap stanza required
end
