# This file was generated by GoReleaser. DO NOT EDIT.
cask "nanoid" do
  desc "A simple, fast, and concurrent command-line tool for generating secure, URL-friendly unique string IDs using the NanoID Go implementation."
  homepage "https://github.com/sixafter/homebrew-nanoid-cli/"
  version "1.33.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nanoid"

  on_macos do
    on_intel do
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.33.0/nanoid_1.33.0_darwin_amd64.tar.gz",
        verified: "github.com/sixafter/nanoid-cli/",
        using: :homebrew_curl
      sha256 "5ecf6937aab2bd397a8389f7ab82560a6a22348051d842bab22f96edbcabb4a9"
    end
    on_arm do
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.33.0/nanoid_1.33.0_darwin_arm64.tar.gz",
        verified: "github.com/sixafter/nanoid-cli/",
        using: :homebrew_curl
      sha256 "86d186a05bd6a99a94e891669cda53fb5d4e850351e6e4a0494dcb8a33b3f464"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.33.0/nanoid_1.33.0_linux_amd64.tar.gz",
        verified: "github.com/sixafter/nanoid-cli/",
        using: :homebrew_curl
      sha256 "00587f9178fa21435a01a4c087669c90d0ec10f8353d2b232e1a75bdb07a9594"
    end
    on_arm do
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.33.0/nanoid_1.33.0_linux_arm64.tar.gz",
        verified: "github.com/sixafter/nanoid-cli/",
        using: :homebrew_curl
      sha256 "c811ceebadee4ac883f6589bc855bfc6547fbfc91b98b38ba304e4bad315d746"
    end
  end

  # No zap stanza required
end
