# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanoid < Formula
  desc "A simple, fast, and concurrent command-line tool for generating secure, URL-friendly unique string IDs using the NanoID Go implementation."
  homepage "https://github.com/sixafter/homebrew-nanoid-cli/"
  version "1.43.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.43.0/nanoid_1.43.0_darwin_amd64.tar.gz"
      sha256 "5f552b45e2914f428169e70a3cc4a818617b46ce678a4a29741ca564ffaf52f6"

      def install
        bin.install "nanoid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.43.0/nanoid_1.43.0_darwin_arm64.tar.gz"
      sha256 "20b37398d61634425512f50c1cbc7ae932c75ebfe0eeb3e7d2ab61b9c3f5df1a"

      def install
        bin.install "nanoid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.43.0/nanoid_1.43.0_linux_amd64.tar.gz"
      sha256 "22330755b8e5dff785ac500234096092662c84d30ba933f20013ebb075804d4a"
      def install
        bin.install "nanoid"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.43.0/nanoid_1.43.0_linux_armv6.tar.gz"
      sha256 "90f5dbc1f59f00ebd0bfecf432fe9586a9886416abd2502242d3aebf9b675b70"
      def install
        bin.install "nanoid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.43.0/nanoid_1.43.0_linux_arm64.tar.gz"
      sha256 "70f972335f664cb98a985c62bcc802e680815977e8b36c397339a44476def200"
      def install
        bin.install "nanoid"
      end
    end
  end
end
