# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanoid < Formula
  desc "A simple, fast, and concurrent command-line tool for generating secure, URL-friendly unique string IDs using the NanoID Go implementation."
  homepage "https://github.com/sixafter/homebrew-nanoid-cli/"
  version "1.17.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.17.0/nanoid_1.17.0_darwin_amd64.tar.gz"
      sha256 "aea13a52fbb04e0a492a3e7cf4f606f426b96680aa7339baa3c540cee3424094"

      def install
        bin.install "nanoid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.17.0/nanoid_1.17.0_darwin_arm64.tar.gz"
      sha256 "827cf0126d8f4480baf2f0d6591d425e151f0c905f7f26b1e186f07e42f1903a"

      def install
        bin.install "nanoid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.17.0/nanoid_1.17.0_linux_amd64.tar.gz"
      sha256 "836e43ab3560dda0fe87b50c6716640769e59eeb8580fa296d31461e97d80452"
      def install
        bin.install "nanoid"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sixafter/nanoid-cli/releases/download/v1.17.0/nanoid_1.17.0_linux_arm64.tar.gz"
      sha256 "33953da4d17e87e6e3ca391996da6cc71f4eced4290452174b21326a6af2b871"
      def install
        bin.install "nanoid"
      end
    end
  end

  test do
    system "#{bin}/nanoid version"
    assert_match "version", shell_output("#{bin}/nanoid --version")
  end
end
